apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app-project-1
  namespace: argocd
spec:
  description: This is my first app project
  sourceRepos:
    - https://github.com/bnelli123/kubernetesDocs.git
  destinations:
    - namespace: dev
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceBlacklist:
    - group: "*"
      kind: "Event"
  # roles:
  #   - name: admin
  #     description: Admin role with full permissions
  #     policies:
  #       - p, proj:app-project-1:admin, applications, *, */*, allow
  #       - p, proj:app-project-1:admin, clusters, *, *, allow
  #       - p, proj:app-project-1:admin, repositories, *, *, allow
  #   - name: read-only
  #     description: Read-only role with view permissions
  #     policies:
  #       - p, proj:app-project-1:read-only, applications, get, */*, allow
  #       - p, proj:app-project-1:read-only, clusters, get, *, allow
  #       - p, proj:app-project-1:read-only, repositories, get, *, allow
  #     groups:
  #       - read-only-group
