apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  namespace: dev
  labels:
    app: redis
spec:
  replicas: 3
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      volumes:
        - name: redis-config
          configMap:
            name: redis-config-map
        - name: redis-secret
          secret:
            secretName: redis-secret
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          env:
            - name: REDIS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-username
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          volumeMounts:
            - name: redis-config
              mountPath: /etc/redis/redis.conf
              subPath: redis.conf
            - name: redis-secret
              mountPath: /etc/redis/secret
              subPath: secretFile.txt
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
        #Add new container
        - name: redis-sidecar
          image: redis-sidecar:latest
          ports:
            - containerPort: 8080
          env:
            - name: SIDE_CAR_ENV
              value: "sidecar-value"
          resources:
            requests:
              memory: "32Mi"
              cpu: "100m"
            limits:
              memory: "64Mi"
              cpu: "200m"
      initContainers:
        - name: init-busybox
          image: busybox
          env:
            - name: LOG_SHIPPER_ENV
              value: "log-shipper-value"
          resources:
            requests:
              memory: "16Mi"
              cpu: "50m"
            limits:
              memory: "32Mi"
              cpu: "100m"
